### ISSUE TITLE
Testing on APi

### ISSUE THREAD

**Issue by su-network** [Google-Developer-Student-Club-RJIT/remotebirds-backend#12]
I think the api need be go through some kind of test in order to provide better result without any **broken functionality.**

**Comment by mr-palindrome** [comment]
Can you elaborate what kind of testing! And what are the test-cases!

**Comment by su-network** [comment]
Talking about CI/CD pipeline.Make easy when someone contribute in **repository** with automated check pass and deployment ready.

**Comment by mr-palindrome** [comment]
> Talking about CI/CD pipeline.Make easy when someone contribute in **repository** with automated check pass and deployment ready.

Okay... please keep me updated regarding this issue!

**Comment by su-network** [comment]
I will sort it out in couple of months.
