### ISSUE TITLE
Acknowledge the Contributors by adding Contributors Section in README.md

### ISSUE THREAD

**Issue by mr-palindrome** [Google-Developer-Student-Club-RJIT/remotebirds-backend#2]
### Proposed Changes

- Add a dynamic Contributors Section in README file
- Add Copyright Logo to the Project at end of README
- Add more helpful links for beginners in Contributing.md (if needed)

**Comment by su-network** [comment]
Assigned to me. I can do

**Comment by mr-palindrome** [comment]
> Assigned to me. I can do

Yeah sure @su-shubham. Go ahead!

But keep in mind that we need a dynamic contributors section which will automatically get updated!

**Comment by su-network** [comment]
#4 Update done . If need  to alter ping me!

**Comment by mr-palindrome** [comment]
Thank you for your valuable contribution!
