### ISSUE TITLE
Add relevant keywords.

### ISSUE THREAD

**Issue by mr-palindrome** [Google-Developer-Student-Club-RJIT/remotebirds-backend#7]
We need more such keywords which are relevant for a job opening tweet.
<img width="738" alt="image" src="https://user-images.githubusercontent.com/56421861/194819190-61197cc1-bfe0-4ce8-bf34-e6c0f33718b1.png">

**Comment by su-network** [comment]
Assigned to me! I am happy to work on it....

**Comment by mr-palindrome** [comment]
Hey @su-shubham!
Thanks for showing interest in our project!
Please keep in mind the keywords should be relevant. Please do unit testing on postman before sending the PR.

**Comment by gaurika05** [comment]
Assign this issue to me. I would be happy to include some good keywords.

**Comment by mr-palindrome** [comment]
> Assign this issue to me. I would be happy to include some good keywords.

Hey @gaurika05 
Thank you for showing interest, but this issue is already assigned to someone else!
You can create any other issue and get it assigned.

**Comment by gaurika05** [comment]
OK

**Comment by mr-palindrome** [comment]
Hey @su-shubham it's been a while! Are you still working on this?

**Comment by su-network** [comment]
#14 Done!
