### ISSUE TITLE
Add filter to ignore tweets in different language other than English.

### ISSUE THREAD

**Issue by mr-palindrome** [Google-Developer-Student-Club-RJIT/remotebirds-backend#8]
There are many such tweets which are in different language.
### Proposed changes
- need to add conditions which will remove such tweets
- 
<img width="590" alt="image" src="https://user-images.githubusercontent.com/56421861/194819899-81e4cc76-a9d1-4f72-9ebb-9aeb6678a0e0.png">

**Comment by piyshkmr** [comment]
hello, can you please assign this issue to me ?

**Comment by mr-palindrome** [comment]
Hey @devocoe! Go ahead!
